config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/ml-ppa/pulsardtpp:
      branch: main
      repo: https://gitlab.com/ml-ppa/pulsardtpp
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/ml-ppa/pulsardtpp git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-amethyst-bracke.sh
        container: qc.acc_slaphappy-asparagus-abyssinian
  QC.Doc:
    repos:
      gitlab.com/ml-ppa/pulsardtpp find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-gold-russel.sh
        container: qc.doc_scummy-rose-shark
      gitlab.com/ml-ppa/pulsardtpp git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-ecru-capybara.sh
        container: qc.doc_crappy-amaranth-fowl
      gitlab.com/ml-ppa/pulsardtpp markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-purple-frog.sh
        container: qc.doc_droopy-grey-urchin
  QC.Lic:
    repos:
      gitlab.com/ml-ppa/pulsardtpp licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-jade-flamingo.sh
        container: qc.lic_hazy-charcoal-tuatara
  QC.Sec:
    repos:
      gitlab.com/ml-ppa/pulsardtpp bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-tomato-bordeaux.sh
        container: qc.sec_bumpy-emerald-tarantula
  QC.Sty:
    repos:
      gitlab.com/ml-ppa/pulsardtpp flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-blue-vulture.sh
        container: qc.sty_paltry-mustard-newt
      gitlab.com/ml-ppa/pulsardtpp oclint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-salmon-uakari.sh
        container: qc.sty_dorky-aquamarine-barracuda
  QC.Uni:
    repos:
      gitlab.com/ml-ppa/pulsardtpp pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-magenta-molly.sh
        container: qc.uni_queasy-yellow-sheepdog
  QC.Ver:
    repos:
      gitlab.com/ml-ppa/pulsardtpp get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-olivine-kiwi.sh
        container: qc.ver_silly-magnolia-camel
timeout: 5400
